server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lba?currentSchema=players
    username: lba
    password: lb4Us3r

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/